### ISSUE TITLE
The given key 'HEROsMod: Quick Stack' was not present

### ISSUE THREAD

**Issue by JavidPack** [JavidPack/HEROsMod#117]
v0.4.12, stable

[11:29:13.888] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.Collections.Generic.KeyNotFoundException: The given key 'HEROsMod: Quick Stack' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at HEROsMod.HEROsModServices.InventoryManager.Update() in HEROsModServices\InventoryManager.cs:line 85
   at HEROsMod.HEROsMod.Update() in HEROsMod.cs:line 502
   at HEROsMod.HerosModSystem.<>c.<ModifyInterfaceLayers>b__1_1() in HerosModSystem.cs:line 29
   at Terraria.UI.GameInterfaceLayer.Draw() in tModLoader\Terraria\UI\GameInterfaceLayer.cs:line 41
   at Terraria.Main.DrawInterface(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 34537
   at Terraria.Main.DoDraw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 49399
   at Terraria.Main.Draw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 48712
   at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 562
   at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 878
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 419
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 231
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 192
   at System.Threading.Thread.StartCallback()

[11:29:15.666] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.Collections.Generic.KeyNotFoundException: The given key 'HEROsMod: Quick Stack' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at HEROsMod.HEROsModServices.InventoryManager.Update() in HEROsModServices\InventoryManager.cs:line 85
   at HEROsMod.HEROsMod.Update() in HEROsMod.cs:line 502
   at HEROsMod.HerosModSystem.<>c.<ModifyInterfaceLayers>b__1_1() in HerosModSystem.cs:line 29
   at Terraria.UI.GameInterfaceLayer.Draw() in tModLoader\Terraria\UI\GameInterfaceLayer.cs:line 41
   at Terraria.Main.DrawInterface(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 34537

**Comment by JavidPack** [comment]
This happens with -quickselect, I think if the game window is inactive while loading? Basically the keybinds aren't initialized in the 1st game update so it errors.
